# Generated by Django 4.2.4 on 2023-08-25 11:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetLocationLat', models.FloatField()),
                ('targetLocationLong', models.FloatField()),
                ('targetLocationAddressFormat', models.TextField()),
                ('limitMembers', models.PositiveSmallIntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Lobby',
                'verbose_name_plural': 'Lobbies',
                'db_table': 'lobby',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latTracks', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('longTracks', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('endedAt', models.DateTimeField()),
                ('maxBPM', models.FloatField()),
                ('bpmArray', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('caloriesBurned', models.PositiveIntegerField(default=0)),
                ('ptsEarned', models.PositiveIntegerField(default=0)),
                ('expEarned', models.PositiveIntegerField(default=0)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lobby')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.runner')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
                'db_table': 'history',
            },
        ),
    ]
