# Generated by Django 4.2.4 on 2023-09-15 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lobby_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.runner')),
            ],
            options={
                'verbose_name': 'LobbyMessage',
                'verbose_name_plural': 'LobbyMessages',
                'db_table': 'lobby_message',
            },
        ),
    ]
