# Generated by Django 4.2.4 on 2023-09-19 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lobby_currentmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lobby',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.runner'),
        ),
    ]
