# Generated by Django 4.2.4 on 2023-09-15 02:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lobby_currentmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='currentMemberID',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=list, size=None),
        ),
    ]
