# Generated by Django 4.2.4 on 2023-09-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lobby_currentmemberid'),
        ('api', '0004_lobby_ended_lobby_owner'),
    ]

    operations = [
    ]
