# Generated by Django 4.2.4 on 2023-09-19 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20230919_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='endedAt',
            field=models.DateTimeField(blank=True),
        ),
    ]
