# Generated by Django 4.2.4 on 2023-09-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_lobby_started_alter_history_endedat_lobbymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='endedAt',
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
